Algoritmo "media_ponderada"

Var

 n : inteiro
 x : real
 y : real
 z : real
 mediap : real
 i : inteiro

Inicio

 escreva("Quantos casos voce vai digitar? ")
  leia(n)
 
 para i de 1 ate n faca
 
 escreval("Digite tres numeros: ")
  leia(x)
   leia(y)
    leia(Z)
    
 
 mediap <- (x * 2 + y * 3 + z * 5 ) / 10
 escreval("MEDIA = ", mediap:3:1)

 fimpara
 


Fimalgoritmo